import AppKit
import Carbon.HIToolbox
import CoreGraphics

public enum InjectionError: Error, LocalizedError {
    case accessibilityNotGranted
    case secureInputActive

    public var errorDescription: String? {
        switch self {
        case .accessibilityNotGranted:
            return "Accessibility permission is required to insert text."
        case .secureInputActive:
            return "A secure input field is active (likely a password box)."
        }
    }
}

/// Writes transcribed text into whatever app currently has keyboard focus.
///
/// Primary path: snapshot clipboard → put text on it (marked transient so
/// clipboard managers skip it) → synthesize ⌘V → restore the clipboard.
/// Fallback path: synthesize raw unicode keystrokes.
@MainActor
public final class TextInjector {
    public enum Method: String, Codable, CaseIterable, Sendable {
        case paste
        case type
    }

    /// Marker types from nspasteboard.org; well-behaved clipboard managers
    /// (Maccy et al.) ignore pasteboard entries carrying them.
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    public init() {}

    /// Injects `text` at the cursor. Throws when it cannot post events; the
    /// caller then falls back to leaving the text on the clipboard.
    public func inject(_ text: String, method: Method, restoreClipboard: Bool) async throws {
        guard AXIsProcessTrusted() else { throw InjectionError.accessibilityNotGranted }
        guard !IsSecureEventInputEnabled() else { throw InjectionError.secureInputActive }

        switch method {
        case .type:
            KeystrokeTyper.type(text)

        case .paste:
            let snapshot = PasteboardSnapshot()
            let pasteboard = NSPasteboard.general
            pasteboard.clearContents()
            let item = NSPasteboardItem()
            item.setString(text, forType: .string)
            item.setData(Data(), forType: Self.transientType)
            item.setData(Data(), forType: Self.autoGeneratedType)
            pasteboard.writeObjects([item])

            postCommandV()

            if restoreClipboard {
                // Paste readers grab the data synchronously on the keystroke;
                // 300 ms is the field-proven safe window before restoring.
                try? await Task.sleep(nanoseconds: 300_000_000)
                snapshot.restore()
            }
        }
    }

    /// Puts text on the clipboard permanently (no restore) — the graceful
    /// degradation when injection isn't possible.
    public func copyOnly(_ text: String) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
    }

    private func postCommandV() {
        let source = CGEventSource(stateID: .combinedSessionState)
        let vKey = CGKeyCode(kVK_ANSI_V)
        guard
            let down = CGEvent(keyboardEventSource: source, virtualKey: vKey, keyDown: true),
            let up = CGEvent(keyboardEventSource: source, virtualKey: vKey, keyDown: false)
        else { return }
        down.flags = .maskCommand
        up.flags = .maskCommand
        down.post(tap: .cghidEventTap)
        up.post(tap: .cghidEventTap)
    }
}
